# Generated by Django 6.0.6 on 2026-06-30 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма'),
        ),
    ]
